# Test program created while learning the uses
import os
a = os.path.join('folder','file.jpg')
print(a)
print(os.sep)
b = os.getcwd()
print(os.getcwd())
os.chdir('d:\\')
print(os.getcwd())
os.chdir(b)
print(os.path.abspath('spam.png'))
print(os.path.abspath('..\\..\\spam.png'))
print(os.path.isabs('..\\..\\spam.png'))
print(os.path.exists('..\\..\\Flutter.txt'))
print(os.path.exists('..\\..\\Pika'))
print(os.path.isfile('..\\..\\Flutter.txt'))
print(os.path.isfile('..\\..\\Pika'))
print(os.path.isdir('..\\..\\Flutter.txt'))
print(os.path.isdir('..\\..\\Pika'))
print(os.path.getsize('..\\..\\Flutter.txt'))
print(os.listdir())
os.makedirs('randome')
#os.makedirs(os.getcwd() + 'faffa\\affa')
print(os.listdir())
